# Generated by Django 3.0.6 on 2020-05-04 23:35

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200505_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=''),
        ),
    ]
