# Generated by Django 3.0.6 on 2020-05-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200505_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
